### ISSUE TITLE
I would like to request the following feature in adminize package

### ISSUE THREAD

**Issue by nyinyiphyo** [hivelocityinc/adminize#10]
- [x] ~~Small panel (Compack View).~~
- [x] Grid for panel. (Move to #19)
- [x] Datetime picker (moved to #17)
- [x] More than one select box in the same `div` without break line.(moved to #18)
- [x] `Info` Flash Message.
- [x] `email`, `number`, `tel` Input Type.
- ~~Graph chart.~~ (invalid)
- [x] Modal Box. (moved to #16)

**Comment by ghost** [comment]
@nyinyiphyo 
Please tell me about detail of the following:

> Small panel (Compack View).
> Grid for panel.
> More than one select box in the same div without break line.

Current status,
Maybe you have to create a new css for your project.

<br>

> Info Flash Message.
> email, number, tel Input Type.
> Modal Box.

I will update to that feature. thank you.

<br>

> Graph chart.

It can be realized by using other framework.
For example:
- https://developers.google.com/chart/
- http://www.chartjs.org/docs/ (Recommended)

**Comment by nyinyiphyo** [comment]
And One additional request,
- `Validation states`, _for show form validation message_.

**Comment by ghost** [comment]
@nyinyiphyo

``` html

<input type="text" class="input--danger" placeholder="danger" value="wrong value">

<!-- shows error message -->
<div class="flash-msg danger">
  <button type="button" class="close js-flmsg-close"></button>
  <p>Error message</p>
</div>
```

If you want to shows a validation message, to use the Flash Message component with `danger` coloring.

**Comment by ghost** [comment]
1) Some feature requests were split. #19 #18 #17 #16 

>  Small panel (Compack View).

I will consider it. and I think, it is not necessary now.
